name: Check and Maturin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  check_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: default
        components: rustfmt, rust-src
    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
    - name: Check
      run: cargo +nightly check --verbose
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release
        rust-toolchain: nightly
  check_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: default
        components: rustfmt, rust-src
#     - name: install-cmake
#       uses: Symbitic/install-cmake@v0.1.0
#     - name: Check
#       run: cargo +nightly build
    - uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: build
        args: --release
        rust-toolchain: nightly
